### ISSUE TITLE
Can't connect to LocalDb

### ISSUE THREAD

**Issue by IeuanWalker** [tareqimbasher/NetPad#108]
Unable to connect to a local database, works fine the SQL Server Management Studio - 
![image](https://github.com/tareqimbasher/NetPad/assets/6544051/628df2eb-6b1a-4812-ab3b-ad2a161287e2)

**Comment by tareqimbasher** [comment]
Could you try it with just 1 backslash `\`?

**Comment by IeuanWalker** [comment]
Ahh ye that works, thanks.
Copied the server name directly from appsettings, so didnt even think there was an issue in it
