### ISSUE TITLE
uncaught exception on startup - non-standard network interfaces

### ISSUE THREAD

**Issue by patanne** [tareqimbasher/NetPad#111]
I just installed the software for the first time. I am using Windows 11. At startup the software is immediately dying with an EACCES exception that appears to be failure to set up a listener. 

See image...
![2023-11-11_11-31-14](https://github.com/tareqimbasher/NetPad/assets/17474951/f26a8d60-6334-4dfb-b565-485acac5a934)

I got to wondering. I run into issues with my own code unless I isolate and use REAL network interfaces. I have VMWare Workstation and Virtual Box installed. Their virtual interfaces for host-only networks cause issues. So I disabled them. Didn't fix it. Then I also disabled the Bluetooth network. The software started right up.
![2023-11-11_11-40-54](https://github.com/tareqimbasher/NetPad/assets/17474951/6f200088-defe-47fa-b706-852c0d71c6ca)

Just letting you know.

**Comment by tareqimbasher** [comment]
This is an interesting problem. Thank you for reporting it.

**Comment by tareqimbasher** [comment]
Closing as environment issue. I added an entry to [Troubleshooting page](https://github.com/tareqimbasher/NetPad/wiki/Troubleshooting)
