### ISSUE TITLE
Support for .NET 8 and C# 12

### ISSUE THREAD

**Issue by lassevk** [tareqimbasher/NetPad#115]
With the recent release of .NET 8 with C# 12, it would be nice if NetPad supported this.

**Comment by jasonswearingen** [comment]
while I "thumbed up", FYI I'm on .net8 but had no problems using netpad to connect /query my database.  (also reference the latest v8 of nuget packages)

**Comment by tareqimbasher** [comment]
.NET 8/C# 12 support is coming in the next day or two, stay tuned!

**Comment by tareqimbasher** [comment]
**Update:** #116

**Comment by tareqimbasher** [comment]
Closing with publish of new v0.6.0 release.
