### ISSUE TITLE
Calling Dump with a title, and then dump without, adds more stuff to the titled region

### ISSUE THREAD

**Issue by lassevk** [tareqimbasher/NetPad#118]
This example:

    10.Dump();
    20.Dump();

produces this output:

    10
    20

However, this example:

    10.Dump("Title");
    20.Dump();
    
produces this:

    | Title
    | 1020

I feel like the expected output should be something like this:

    | Title
    | 10
    20

Tested in NetPad 0.6.0 on Windows.

**Comment by lassevk** [comment]
If I manually add an empty line between the two, it breaks the cycle:

    10.Dump("Ttle");
    "".Dump();
    20.Dump();

Output:

    | Title
    | 10
    20

**Comment by tareqimbasher** [comment]
Thank you for reporting this. Fix will go out with next release.
