### ISSUE TITLE
Feature request: Reuse nuget.config nuget sources for package discovery

### ISSUE THREAD

**Issue by lassevk** [tareqimbasher/NetPad#119]
We publish nuget packages on Github, in our private organization. It would be nice if the nuget source I have added to my nuget.config file is honored, so that I can use packages we've made, without having to browse for and refer to the base assemblies locally.

**Comment by tareqimbasher** [comment]
This is planned. I'll bump it up on list of priorities :+1:

**Comment by tareqimbasher** [comment]
#193 adds support for reading multiple repositories from `Nuget.Config` file. Will go out with next release.
