### ISSUE TITLE
It can no be installed on MacOS 13.4.1

### ISSUE THREAD

**Issue by Coder7777** [tareqimbasher/NetPad#120]
Hi, I try to run it on my MacOS m1, but it seems not be satisfied.

I tried to redownload it and other versions, but it always shows the same result.

<img width="260" alt="image" src="https://github.com/tareqimbasher/NetPad/assets/17242425/eee1792d-d0c4-4647-892b-bdb1db597fc0">

**Comment by tareqimbasher** [comment]
See #113

**Comment by Coder7777** [comment]
> See #113

Oh, Awesome. 

You ended my life that switching between Mac OS and Windows just for debugging Linq by LinqPad.

**Comment by tareqimbasher** [comment]
I hear ya, that was my life too before NetPad :grin: I'm glad you're enjoying it!

Do note though that NetPad does not, _yet_, have a debugger. So you won't be able to set breakpoints and debug your code as you would in LINQPad. It's on the roadmap though.
