### ISSUE TITLE
Feature request: Setting to change the font size of the Output pane

### ISSUE THREAD

**Issue by gicque** [tareqimbasher/NetPad#121]
As a user with visual preferences or specific accessibility needs, having the ability to customize the font size in the Output pane would enhance the overall usability of the application, ensuring a more comfortable and personalized viewing experience.

**Comment by tareqimbasher** [comment]
The plan is to provide custom CSS styling of output to users so you can customize it however you'd like. I'll give this more attention on the priority list.

**Comment by tareqimbasher** [comment]
@gicque support was added for customizing output styling in v0.7.1.

See: https://github.com/tareqimbasher/NetPad/wiki/Styling#customizing-output
