### ISSUE TITLE
[Mac] "File" menu options disappear after accessing settings window

### ISSUE THREAD

**Issue by noahkiss** [tareqimbasher/NetPad#125]
After opening and closing the settings window, the File menu is (empty). 

Also shows (empty) on the settings menu, so I assume what's happening is the app is not switching back to the main window's File menu list.

<img width="645" alt="Screenshot 2023-11-25 at 10 10 54 AM" src="https://github.com/tareqimbasher/NetPad/assets/22437387/4711b0ec-880e-4eb2-829d-4cd9e5ffc080">
<img width="644" alt="Screenshot 2023-11-25 at 10 12 17 AM" src="https://github.com/tareqimbasher/NetPad/assets/22437387/57264df1-0993-44fe-945a-1d6feb4f62f1">
<img width="608" alt="Screenshot 2023-11-25 at 10 20 07 AM" src="https://github.com/tareqimbasher/NetPad/assets/22437387/c95edeb9-b338-47e3-a982-b9529da76e87">

**Comment by tareqimbasher** [comment]
Will investigate and push a hotfix soon.

Is the problem consistent, meaning does the File menu go empty everytime you open and close the Settings menu or is it sporadic?
