### ISSUE TITLE
ScriptDirectoryPath could use protected folder

### ISSUE THREAD

**Issue by sebastienros** [tareqimbasher/NetPad#134]
In my domain the `%userprofile%/Document` folder is restricted and random application are not allowed to alter it. In my case it make NetPad hang on startup because it tries to create the `Scripts` folder.

Instead of using `Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)` maybe it could use the local app data folder too. Or detect that it's not allowed (timeout) and fallback to something else, or just skip this part.

As a mitigation I believe I can setup another folder in config.

**Comment by tareqimbasher** [comment]
I agree. Does it hang for some time and then eventually open or does it hang indefinitely?

You are correct, you can setup a different folder in the config. If you can't get to the UI to do it, you can edit the `settings.json` file (the `scriptsDirectoryPath` property).
