### ISSUE TITLE
SQL Server Connection with Integrated Security

### ISSUE THREAD

**Issue by christophwille** [tareqimbasher/NetPad#135]
I can connect to .\SQLEXPRESS nicely with Azure Data Studio
![image](https://github.com/tareqimbasher/NetPad/assets/344208/3e5d993d-480e-4973-9254-ba4197af54b7)
But with NetPad, I only have the options of No Auth and User & Password. Is the Windows Authentication scenario supported or am I simply missing how to get it working?

**Comment by tareqimbasher** [comment]
It is indeed missing. Will add it in soon.

**Comment by tareqimbasher** [comment]
**Update** - You will be able to modify the generated connection string and add `Integrated Security=SSPI` and any other config options you like. The solution is already built and will go out with v0.7.0

**Comment by tareqimbasher** [comment]
PR: #143

**Comment by tareqimbasher** [comment]
PR is merged and will go out in v0.7.0
