### ISSUE TITLE
"Unable to find an interpreter" when running the downloaded exe

### ISSUE THREAD

**Issue by dlwiii** [tareqimbasher/NetPad#140]
Downloaded onto Ubuntu.  Ran chmod a+x, then tried the exe:

$ ./netpad-0.6.0-win-x64.exe 
run-detectors: unable to find an interpreter for ./netpad-0.6.0-win-x64.exe

dotnet 7.0.114 is installed in /usr/share/dotnet

What am I missing?

**Comment by tareqimbasher** [comment]
The `.exe` package is for Windows. On Ubuntu, you want to download the `netpad-0.6.0-linux-amd64.deb` file instead and then install that.

```shell
sudo dpkg –i /path/to/netpad-0.6.0-linux-amd64.deb
```

**Comment by tareqimbasher** [comment]
Feel free to reopen if not resolved
