### ISSUE TITLE
Please provide option to not pluralize the database

### ISSUE THREAD

**Issue by grosch** [tareqimbasher/NetPad#141]
I'm not seeing it, sorry if it already exists.  I'm looking for a way to have the `--no-pluralize` flag sent when you're generating the schema.

**Comment by tareqimbasher** [comment]
It does not currently exist. Will add it!

**Comment by willsmith9182** [comment]
Further to this, is there a way to specify which schemas you actually want scaffolding?

`--schema <SCHEMA_NAME>` can be used for each schema you want included when calling ef scaffold.

I have a fun situation where I have tables with the same name in different schemas, and even schemas I don't want to query/scaffold.

**Comment by tareqimbasher** [comment]
That also does not yet exist. I will look into adding more control over the scaffolding process in the near future including controlling the schemas you want to scaffold.

**Comment by tareqimbasher** [comment]
PR #147 

Will go out with 0.7.0
