### ISSUE TITLE
Cannot add SQL connection: scaffolding requires .net 6

### ISSUE THREAD

**Issue by nZeus** [tareqimbasher/NetPad#146]
Hello,

I use MacOS, and I have .NET 7 and .NET 8 installed. NetPad is v0.6.0, ef tool is v8.0.

I'm trying to add a SQL connection, but it crashes with the following error:

`One or more errors occurred. (Scaffolding process failed with exit code: 150.`  ... `You must install or update .NET to run this application.`:

<img width="680" alt="image" src="https://github.com/tareqimbasher/NetPad/assets/2727326/29a51658-993d-4237-899a-1b9e3c272d26">

**Comment by tareqimbasher** [comment]
Correct, as mentioned in README, .NET 6 runtime (or SDK) is required if you want to add connections. I'm working on removing that dependency in a futuree release, but for now you do infact need .NET 6.0 runtime or SDK installed.

**Comment by nZeus** [comment]
Ah, indeed. I didn't see it is mentioned in the readme. Thank you for your work! It's a great tool!

**Comment by tareqimbasher** [comment]
Thank you, glad you're enjoying it!
