### ISSUE TITLE
Feature Request: Use fixed assembly name when executing NetPad query.

### ISSUE THREAD

**Issue by filzrev** [tareqimbasher/NetPad#157]
Currently NetPad creates different `assembly name` each time a query is executed.

**Test query** 

```
Assembly.GetExecutingAssembly().FullName.Dump();
Assembly.GetExecutingAssembly().CodeBase.Dump();
```

**Output**
```
`NetPad_CompiledAssembly_Script 1_b2b3d5aa-ffb7-4a2e-b122-55f0add3514a, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
`file:///C:/Users/admin/AppData/Local/Temp/NetPad/Processes/371cbddd-91b1-4c40-9943-70abbe1f6d60/Script_1.dll`
```

If it can use fixed assembly name (e.g. `NetPadQuery`)
It can access internal types of external DLLs. (If external DLL using `InternalsVisibleToAttribute`).

 [LINQPad supports this feature](https://www.linqpad.net/FAQ.aspx) with `[InternalsVisibleTo("LINQPadQuery")]`

**Comment by tareqimbasher** [comment]
Sure, good idea. Will go out with next release!

**Comment by tareqimbasher** [comment]
PR merged. Similar to LINQPad, you'll be able to use:

```csharp
[InternalsVisibleTo("NetPadScript")]
```
