### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by peter-nguyen-contemi** [tareqimbasher/NetPad#159]
Hi, NetPad 0.6.1-win-x64 suddenly stops starting today on my Windows 11 machine. Could you please investigate what went wrong and how I can make it work again. Below are all information that I think are helpful for troubleshooting. Thank you.

[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: listen EACCES: permission denied ::1:57931
    at Server.setupListenHandle [as _listen2] (node:net:1468:21)
    at listenInCluster (node:net:1533:12)
    at GetAddrInfoReqWrap.doListen [as callback] (node:net:1682:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:8)

[OK]

![image](https://github.com/tareqimbasher/NetPad/assets/133377780/fa0aeb94-a723-4200-8968-382fd6a21c28)

```
dotnet --list-sdks
8.0.101 [C:\Program Files\dotnet\sdk]

dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

OS version:
Edition	Windows 11 Pro
Version	23H2
Installed on	‎9/‎14/‎2023
OS build	22631.3085
Experience	Windows Feature Experience Pack 1000.22684.1000.0

**Comment by tareqimbasher** [comment]
Thank you for reporting this. As a test can you try installing .NET 6 SDK and see if it launches without an error?

**Comment by alexanderluettig** [comment]
Hey,
Im getting the same error
![image](https://github.com/tareqimbasher/NetPad/assets/129614217/1ff3caf6-e8f4-4c0b-a595-127dc3b75c10)
Also tried to update node but that didnt work either

**Comment by martinzima** [comment]
I started getting this error today too, I'm not able to run NetPad anymore. Tried upgrading to latest NetPad version and reinstalling it with no help. FWIW, I'm running Windows 10.

**Comment by alexanderluettig** [comment]
> Hey, Im getting the same error ![image](https://private-user-images.githubusercontent.com/129614217/303920565-1ff3caf6-e8f4-4c0b-a595-127dc3b75c10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzk2NTMsIm5iZiI6MTcxMjIzOTM1MywicGF0aCI6Ii8xMjk2MTQyMTcvMzAzOTIwNTY1LTFmZjNjYWY2LWU4ZjQtNGMwYi1hNTk1LTEyN2RjM2I3NWMxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQxNDAyMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTkwMmZhOGFkZWQyNmViZWI2MDAxZGQzM2I1ZGRlMzk2OGM1OWRmYjE0ZWY5NTcyYjJkZDk4YmUyNTMyNzg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AUncIzTFZx-KQ94M0imAJimLqg3_3GPv4QLwJUNJuIk) Also tried to update node but that didnt work either

updating to netpad 0.7 fixed it for me

**Comment by alexanderluettig** [comment]
> > Hey, Im getting the same error ![image](https://private-user-images.githubusercontent.com/129614217/303920565-1ff3caf6-e8f4-4c0b-a595-127dc3b75c10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzk2NTMsIm5iZiI6MTcxMjIzOTM1MywicGF0aCI6Ii8xMjk2MTQyMTcvMzAzOTIwNTY1LTFmZjNjYWY2LWU4ZjQtNGMwYi1hNTk1LTEyN2RjM2I3NWMxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQxNDAyMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTkwMmZhOGFkZWQyNmViZWI2MDAxZGQzM2I1ZGRlMzk2OGM1OWRmYjE0ZWY5NTcyYjJkZDk4YmUyNTMyNzg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AUncIzTFZx-KQ94M0imAJimLqg3_3GPv4QLwJUNJuIk) Also tried to update node but that didnt work either
> 
> updating to netpad 0.7 fixed it for me

It broken again :D

**Comment by tareqimbasher** [comment]
I assume downgrading to 0.6.1 doesn't help? Could you try going over your network connections and seeing if disabling any of them fixes the issue? See: #111

**Comment by tareqimbasher** [comment]
I assume downgrading to 0.6.1 doesn't help? Could you try going over your network connections and seeing if disabling any of them fixes the issue? See: #111

Also linking this SO answer if it helps: https://stackoverflow.com/questions/59428844/listen-eacces-permission-denied-in-windows

I haven't been able to replicate the error which makes it really hard to figure out a cause and solution.

**Comment by alexanderluettig** [comment]
> I assume downgrading to 0.6.1 doesn't help? Could you try going over your network interfaces and seeing if disabling any of them fixes the issue? See: #111

Ok. I tried disabling some of my network interfaces and it seems that this is the problem:
![image](https://github.com/tareqimbasher/NetPad/assets/129614217/22ffdcc9-7543-4fac-96a1-edd49e71d22f)
Disabling my wireless interface fixed it for me.
And even after renabling it Netpad will start normally now.

Weird :D

**Comment by tareqimbasher** [comment]
Great! Thanks for reporting back. Seems to be some network interfaces are keeping ports busy or inaccessible on Windows.

@peter-nguyen-contemi @martinzima 👆

**Comment by tareqimbasher** [comment]
Closing as environment issue. I added an entry to [Troubleshooting page](https://github.com/tareqimbasher/NetPad/wiki/Troubleshooting)
