### ISSUE TITLE
relation "Persons_HIDDEN" does not exist

### ISSUE THREAD

**Issue by mortenmoulder** [tareqimbasher/NetPad#165]
Might be related to #70.

Using PostgreSQL database. Tables are created using Entity Framework migrations. Running on Mac with a M2 Pro.

When I hover the tables, I see:

```
Table name: Houses
Table name: Persons_HIDDEN
```

Not all `_HIDDEN` tables are problematic, though. Some work perfectly fine. Not entirely sure why the `_HIDDEN` is necessary, but is there a way to bypass it? I can't even write a simple `SELECT * FROM "Persons";` without getting errors. Thanks!

**Comment by tareqimbasher** [comment]
I needed the `_HIDDEN` piece for a technical challenge I had while writing the `DbContext` for scripts that I have bypassed in the soon-to-be-released v0.7.0. That should solve the issue.

I'll ping here once the new version is out.

**Comment by tareqimbasher** [comment]
@mortenmoulder [v0.7.0](https://github.com/tareqimbasher/NetPad/releases/tag/v0.7.0) is released. Give it a whirl and let me know if it solves your issue.

**Comment by tareqimbasher** [comment]
Closing this for now. Please feel free to reopen it if you're still having issues.
