### ISSUE TITLE
Error in Explorer Connections is not readable

### ISSUE THREAD

**Issue by antonklimov** [tareqimbasher/NetPad#171]
The error resulting from scaffolding is not readable. It's possible to do `Toggle Developer Tools` and search for it, but I think it should be possible to view the whole error without doing that.
<img width="1046" alt="image" src="https://github.com/tareqimbasher/NetPad/assets/26126237/8c9a6417-0db4-4078-9065-ac497ee2db69">

**Comment by tareqimbasher** [comment]
The full error shows if you hover over that red message. I'll add a better way to view it. You can also find the log file by going to `Settings > Open App Data Folder > Logs folder`

**Comment by antonklimov** [comment]
Thank you, yes it actually does show the error after a couple of seconds on hover.

**Comment by tareqimbasher** [comment]
#202 adds a way to copy the error text to the clipboard by just clicking the error bubble. Will go out with next release.
