### ISSUE TITLE
I just facing the exception in my first running : Unhandled exception. System.BadlmageFormatException: An attempt was made to load a program with an incorrect format.

### ISSUE THREAD

**Issue by imfine-sd** [tareqimbasher/NetPad#174]
![pic1](https://github.com/tareqimbasher/NetPad/assets/53457765/125308b8-9c65-431c-b5f2-caa9dba0fd4b)

*My mac info : 
- M1 macbook pro
- Sonoma 14.0
- .Net 8 installed 

How I fix that issue ?

**Comment by tareqimbasher** [comment]
Do you have .NET 6 installed also?

**Comment by imfine-sd** [comment]
> Do you have .NET 6 installed also?

![image](https://github.com/tareqimbasher/NetPad/assets/53457765/399bdf8d-cf3c-40ba-94b6-b2994f7736f5)
Yes .NET6 Installed.

**Comment by tareqimbasher** [comment]
Next check that you have the ARM version of the .NET SDK installed. The error you reported typically means an assembly is not compatible with your processor architecture.

**Comment by imfine-sd** [comment]
I installed new version 0.7.0, and it worked.
