### ISSUE TITLE
select all in the results pane should only select the content of the results pane

### ISSUE THREAD

**Issue by patanne** [tareqimbasher/NetPad#178]
I am on a Mac. I also tested this on Windows. If you hit ctrl-A or cmd-A, every piece of content from every field, box, and pane is selected. The correct behavior should be only to select the content from within the selected pane, in this case the results pane.

Great product. This one is a tweak, but an important one for some DevOps workflows.

**Comment by tareqimbasher** [comment]
I agree its annoying :smile: I wish HTML made this easier to do. Alas, I'll get it added. Thank you for the suggestion, and glad you're enjoying it!

**Comment by tareqimbasher** [comment]
Fixed in linked PR. Will go out with next release.
