### ISSUE TITLE
Could not compile data connection assembly CS7013

### ISSUE THREAD

**Issue by surfmuggle** [tareqimbasher/NetPad#190]
I just discovered and started to use NetPad. I tried to create a connection string but got the error

> Could not compile data connection assembly. Compilation failed with the following diagnostics: (56,20): error CS7013: The name "<...

Steps taken
 - Add a "New Data Connection" to a local sqlite database. 
 - Use the default values and pick a local database file
 - click 'Save'

### Problem
 - The error message is not fully readable. 

### Expected 
 - Each error message is fully readable 

Possible cause of the error
 - The sqlite-database file has only 1 table which is incomplete: it has no columns and no rows 

Running this 

```SQL
SELECT type, name, tbl_name, rootpage, sql  FROM sqlite_master;
```

returns

 | type  |  name  | tbl_name |  rootpage | sql                    |
 | ----- | ------ | -------- | --------- | ---------------------- |
 | table |   a    |   a      |       2   | CREATE Table "a" (.... |

The sql looks like this but with about 5000 rows

```sql
CREATE TABLE "a"(
"Model;Chassis no. ;Chassis no. 17-digits;SomeDate;Invoice_No;Invoice date;Support;Anfrage 1
a;b;c;d;e;f;g;h;
a;b;c;d;e;f;g;h;
a;b;c;d;e;f;g;h;
...
;;;;;;;
;;;;;;  241.223;
;;;;;;;
...
;;;;;;;
;;;;;;;
;;;;;;;
" TEXT)
```

Running `SELECT * FROM a` returns 0 rows. 

### NetPad Screenshot

My NetPad 0.7 looks like this 
![NetPad_error](https://github.com/tareqimbasher/NetPad/assets/1271555/36500018-b655-4ee2-ac12-97735e4a2303)

**Comment by tareqimbasher** [comment]
Hello. I'm trying to replicate the issue. Can you provide me with the SQL to create the table `a`? The error `CS7103` typically means that the name of property or member exceeds the maximum length allowed. You mentioned when you run:

```sql
SELECT type, name, tbl_name, rootpage, sql  FROM sqlite_master;`,  the SQL for table `a`
```

is:

```sql
CREATE TABLE "a"(
"Model;Chassis no. ;Chassis no. 17-digits;SomeDate;Invoice_No;Invoice date;Support;Anfrage 1
a;b;c;d;e;f;g;h;
a;b;c;d;e;f;g;h;
a;b;c;d;e;f;g;h;
...
;;;;;;;
;;;;;;  241.223;
;;;;;;;
...
;;;;;;;
;;;;;;;
;;;;;;;
" TEXT)
```

If that's true, then it seems you somehow have that huge string as a column name. In that case, when EF Core scaffolds your database it will generate a property name that is very long, thus giving you the `CS7013` error.

**Comment by surfmuggle** [comment]
It may be better to delete this issue so that others do not stumble over this none netpad issue.

**Comment by tareqimbasher** [comment]
Thank you for the update @surfmuggle!
