### ISSUE TITLE
Clicking link makes application unusable

### ISSUE THREAD

**Issue by i2van** [tareqimbasher/NetPad#192]
## System

Windows 10, NetPad v0.7.0

## Script

```csharp
O2Html.Dom.TextNode.RawText("<a href='https://google.com'>Heading 1</a>").Dump();
```

## Actual

![image](https://github.com/tareqimbasher/NetPad/assets/5464660/193b40da-f3cb-4065-b8f5-142e04fb2cbd)

And there is no way to get back to the editor.

Also error is not displayed all the time.

## Expected

The way LINQPad works:

- `Left click` opens link in the default browser.
- `Middle click` opens in the embedded browser in a separate window.

**Comment by tareqimbasher** [comment]
Ya I tried getting that implemented for the release but didn't make it. In the meantime try adding `target=_"blank"`to your link.

**Comment by i2van** [comment]
> Ya I tried getting that implemented for the release but didn't make it. In the meantime try adding `target="_blank"`to your link.

It opens link in separate NetPad window, which is weird.
