### ISSUE TITLE
Intellisense not works on Mac arm

### ISSUE THREAD

**Issue by kostyatab** [tareqimbasher/NetPad#194]
I'm using NetPad on a Mac with arm and intellisense doesn't works.

### Screenshot
![CleanShot 2024-04-17 at 14 49 32@2x](https://github.com/tareqimbasher/NetPad/assets/1058121/1bfc483a-bfd1-4788-a962-50286e092c52)

**Comment by tareqimbasher** [comment]
Could you please provide:

1. The result of `dotnet info`
2. Inspect your NetPad logs and tell me if you see anything interesting. You can find them by going to `NetPad Settings > Open App Data Folder > Logs folder`

**Comment by tareqimbasher** [comment]
@kostyatab any update?

**Comment by kostyatab** [comment]
I deleted the folder .local/share/NetPad/OmniSharp and everything is working now

**Comment by tareqimbasher** [comment]
Thanks for the update @kostyatab. Coding issue.
