### ISSUE TITLE
Console.Write(Line) output doesn't return in correct order

### ISSUE THREAD

**Issue by toanq** [tareqimbasher/NetPad#195]
I'm using NetPad v0.7.0 on Windows 11 Version 23H2 (OS Build 22635.2921).

Running this snippet:

```cs
public class XXX {
    public IEnumerable<int> Integers()
    {
        yield return 1;
        yield return 2;
        yield return 4;
        yield return 8;
        yield return 16;
        yield return 16777216;
    }
    public static void Main()
    {
        var x = new XXX();
        x.Consumer();
    }
    public void Consumer()
    {
        foreach (int i in Integers())
        {
            Console.Write($"{i}\n".Dump());
        }
    }
}
```

Result:
![image](https://github.com/tareqimbasher/NetPad/assets/50648031/a6cf442e-80a6-4ccf-9706-6ba1349b11aa)

The `Console.Write` result should be the same as the one with `Dump`.

**Comment by tareqimbasher** [comment]
Please see #89. The problem is you're defining a new entry point by declaring `static void Main()`

**Comment by toanq** [comment]
Wow, I didn't know that, thank you very much for your detailed explanation.
