### ISSUE TITLE
Mac Arm64 release will not open at all

### ISSUE THREAD

**Issue by marknuzz** [tareqimbasher/NetPad#207]
Error:

"The app has been modified or damaged"

Help text:

The app has been modified, and its code does not match the original [signed](https://support.apple.com/guide/?platform=mac&product=mac-help&vanityname=signed&version=14.0&locale=en_US&topicid=GLOS09DCC3E0&type=ddm&platformOSVersion=14.0&aside=true) code. The app may be broken or corrupted, or it may have been tampered with. If you think that an app has been damaged or tampered with, you should delete it by dragging it to the Trash.

Some apps and tools, such as AppleScript or JavaScript applications and some legacy tools, modify themselves after signing. These types of apps cannot be opened unless you override the security settings on your Mac. See [Open an app by overriding security settings](https://support.apple.com/guide/?platform=mac&product=mac-help&vanityname=open-an-app-by-overriding-security-settings&version=14.0&locale=en_US&topicid=MH40617&type=ddm&platformOSVersion=14.0).

To learn how to protect your Mac from harmful software, see [Protect your Mac from malware](https://support.apple.com/guide/?platform=mac&product=mac-help&vanityname=protect-your-mac-from-malware&version=14.0&locale=en_US&topicid=MH40596&type=ddm&platformOSVersion=14.0).

See also
[Change Lock Screen settings on Mac](https://support.apple.com/guide/?platform=mac&product=mac-help&vanityname=change-lock-screen-settings-on-mac&version=14.0&locale=en_US&topicid=MH11784&type=ddm&platformOSVersion=14.0)

**Comment by tareqimbasher** [comment]
@marknuzz can you check [the troubleshooting page](https://github.com/tareqimbasher/NetPad/wiki/Troubleshooting#netpad-is-damaged-and-cant-be-opened) and try the fix there. Let me know if that does not solve your issue.

**Comment by tareqimbasher** [comment]
If you mean syntax tree visualizer, then you're in luck, I just finished that feature and it will go out in the next release pretty soon.

![image](https://github.com/tareqimbasher/NetPad/assets/8684786/c1966fa5-6341-4dfd-a881-97b5d9a8de60)

If that's not it, please share what you're looking for, I'd love to get your feedback. And if you're still having the issue running NetPad, I'd be happy to help.

**Comment by tareqimbasher** [comment]
@marknuzz I'm reopening the issue just in case users don't get notifications for new comments on closed issues.

**Comment by tareqimbasher** [comment]
Sounds good. Although if you're using an ARM laptop, the x64 version noticeably less performant on ARM processors than the ARM version. If the trick from the troubleshooting page didn't help and you still can't get v0.7.1 running, can you try v0.7.0 and see if maybe its something about v0.7.1 that your machine doesn't like.

I'm also available on Discord. Feel free to join there as well and message me anytime.

**Comment by Chris-Kim** [comment]
Same here. Getting an error at launch saying that the file is damaged. 

Mac with M1 Max

**Comment by tareqimbasher** [comment]
@Chris-Kim have you tried the solution explained here: https://github.com/tareqimbasher/NetPad/wiki/Troubleshooting

**Comment by tareqimbasher** [comment]
@marknuzz v0.7.2 is released with a Syntax Tree visualizer!

**Comment by tareqimbasher** [comment]
@marknuzz I know its annoying but you won't have to do that anymore once I get around to getting the app signed. Let me know how you like the Syntax Tree visualizer!

**Comment by tareqimbasher** [comment]
Sorry just saw you created an issue with your suggestions. I'll take a look!
