### ISSUE TITLE
Max Collection Length allowing only 10,000 instead of 100,000

### ISSUE THREAD

**Issue by YaMoef** [tareqimbasher/NetPad#209]
When entering manually 100,000 it will go back to empty and setting 10,000 and clicking the up arrow doesn't change it anymore, before 10,000 it does up it.
![image](https://github.com/tareqimbasher/NetPad/assets/34712836/f6cea40c-5b50-4fec-a191-b4fa57410130)

**Comment by YaMoef** [comment]
I think the issue is in `src/Apps/NetPad.Apps.App/App/src/windows/settings/results-options-settings/results-options-settings.html`. I will take a look later today if I can fix this locally
![image](https://github.com/tareqimbasher/NetPad/assets/34712836/dd11e175-f88f-4fcb-96f9-0778e568ac9f)

**Comment by tareqimbasher** [comment]
@YaMoef Yep, I think that's the issue. I will fix this for next release. Thank you for identifying the problem!
