### ISSUE TITLE
Intellisene not working on macOS

### ISSUE THREAD

**Issue by randelramirez** [tareqimbasher/NetPad#214]
Intellisense/Code highlighting not working on macOS

**Comment by randelramirez** [comment]
I found a quick workaround related to: https://github.com/tareqimbasher/NetPad/issues/208

I just installed .NET 7 and it works now

**Comment by tareqimbasher** [comment]
Yes, fix will be included in next release where you won't need .NET 7 installed.

**Comment by sonerfromnurland** [comment]
> Yes, fix will be included in next release where you won't need .NET 7 installed.

Is there any estimation for that release?

**Comment by tareqimbasher** [comment]
@sonerfromnurland sometime in the next 2 weeks. Issue #208 also lists another solution in the meantime: delete the global.json file.

**Comment by sonerfromnurland** [comment]
> @sonerfromnurland sometime in the next 2 weeks, plan is sooner than that though. Issue #208 also lists another solution in the meantime: delete the global.json file.

@tareqimbasher Thank you, Eid-ul-Adha mubarak.

**Comment by tareqimbasher** [comment]
@sonerfromnurland thank you! Eid Mubarak to you too brother 🎉 May it be a blessing to you and your loved ones.

**Comment by tareqimbasher** [comment]
@randelramirez @sonerfromnurland [v0.7.2](https://github.com/tareqimbasher/NetPad/releases/tag/v0.7.2) is released with this bug fixed!
