### ISSUE TITLE
weired behaviour when calling multiple Console.ReadLine() methods, user input got stuck

### ISSUE THREAD

**Issue by pinkli** [tareqimbasher/NetPad#218]
when call multitple  Console.ReadLine(), I get no user input from the second or the third call.
demo code as below 
```cs
string? userinput;

Console.Write("User1 > ");
userinput = Console.ReadLine();
Console.WriteLine(userinput);

Console.Write("User2 > ");
userinput = Console.ReadLine();
Console.WriteLine(userinput);

Console.Write("User3 > ");
userinput = Console.ReadLine();
Console.WriteLine(userinput);

Console.Write("User4 > ");
userinput = Console.ReadLine();
Console.WriteLine(userinput);
```
sometimes it stops at printing "User3 >" without reading the actual user input, sometimes it stops at "User2 >"; 
"User4 >" never prints in my machine. sometimes the NetPad got freeze not responding. 
I'm using Mac X64 Sonoma 14.5, NetPad 0.7.1, .Net 8.

![WX20240620-120307@2x](https://github.com/tareqimbasher/NetPad/assets/1488256/dfea79f3-6291-4141-a7c8-c0b39ded7a36)

**Comment by tareqimbasher** [comment]
Hmm interesting. I'll take a look! Thank you for reporting.

**Comment by tareqimbasher** [comment]
[v0.7.2](https://github.com/tareqimbasher/NetPad/releases/tag/v0.7.2) is released with this bug fixed!
