### ISSUE TITLE
Intellisense broken after upgrading to 7.1

### ISSUE THREAD

**Issue by lassevk** [tareqimbasher/NetPad#220]
I went from 6.1 to 7.1, and after that there is no working intellisense.

I see previous mentions about intellisense not working when .NET 7 is not installed, does the new version *require* .NET 9 preview to be installed, since it mentions supporting it?

**Comment by tareqimbasher** [comment]
No it does not require .NET 9, but it requires .NET 7 to be installed. It was a goof on my part of mistakenly including a `global.json` file in the packaged app that requires .NET 7 to be installed. OmniSharp reads that and will only work if .NET 7 is installed. New version will be released in the next few days hopefully, and will resolve the issue. For now you can just delete the `global.json` file from your installation or install .NET 7.

**Comment by tareqimbasher** [comment]
@lassevk [v0.7.2](https://github.com/tareqimbasher/NetPad/releases/tag/v0.7.2) is released with this bug fixed!

**Comment by jwallet** [comment]
it was not enough for me even with net core version 7, on my mac

```
➜  dotnet --list-sdks
6.0.421 [/usr/local/share/dotnet/sdk]
7.0.201 [/usr/local/share/dotnet/sdk]
8.0.100 [/usr/local/share/dotnet/sdk]
8.0.101 [/usr/local/share/dotnet/sdk]
8.0.201 [/usr/local/share/dotnet/sdk]
8.0.203 [/usr/local/share/dotnet/sdk]
8.0.204 [/usr/local/share/dotnet/sdk]
8.0.302 [/usr/local/share/dotnet/sdk]
```

I had to delete many netpad local app data files in order to make the omnisharp work again.

> bottom-right corner of main window, there is a settings icon ⚙️ , this opens a modal, in the bottom left corner you will find "Open Add Data Folder"

- settings.json
- key-values.txt
- Logs (folder)
- Omnisharp (folder)
