### ISSUE TITLE
NetPad does not handle Windows usernames that contains spaces

### ISSUE THREAD

**Issue by michaelrogers0** [tareqimbasher/NetPad#221]
My username on Windows contains a space, like "John Doe" (space in between first and last name).
When running a simple single line script such as:
"Hello World from NetPad!".Dump();

I get the following error:
"Could not execute because the specified command or file was not found.
  * You intended to execute a .NET program, but dotnet-C:\Users\John does not exist.
  * You misspelled a built-in dotnet command.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

Possible reasons for this include:"

No "possible reasons" are actually listed, the error appears to be truncated. 

I have already tried manually setting the following paths to be non-default paths that do not contain spaces:
- the "Scripts" path defined in the Settings screen
- the "Package Cache" path defined in the Settings screen
- the "autoSaveScriptsDirectoryPath" path defined in C:\Users\John Doe\AppData\Local\NetPad\settings.json

I could not find any additional path's being defined elsewhere in the Settings screen nor in config files so I am assuming the path that is causing a problem is being derived in the code.

Changing the above paths did *not* fix the issue, I received the same error message after fully exiting NetPad, then restarting NetPad and retrying the script. The problem happens both with the installed version of NetPad *and* the .zip version of NetPad.

I am running NetPad on a Windows 10 Pro x64 machine with all Windows updates applied.

**Comment by tareqimbasher** [comment]
Thanks for the report. Will include fix in the next version to be released in the next couple days

**Comment by michaelrogers0** [comment]
@tareqimbasher Thank you!

**Comment by michaelrogers0** [comment]
@tareqimbasher I can confirm that this issue has been resolved in the new 0.7.2 release. Thank you for the quick fix!

**Comment by tareqimbasher** [comment]
@michaelrogers0 thank you for confirming!
