### ISSUE TITLE
incorrect nuget package version comparison

### ISSUE THREAD

**Issue by WeihanLi** [tareqimbasher/NetPad#227]
![image](https://github.com/tareqimbasher/NetPad/assets/7604648/7881a139-1f68-4a7f-b22f-fb9d7e7cf330)

as the image shown, I'm using the latest preview version `0.22.0-preview-20240629-121817`

it prompts that there's a later version of this package `0.21.0`

while the `0.21.0` should be a previous version other than a later version

**Comment by tareqimbasher** [comment]
Thanks for the report. I'll get that fixed!

**Comment by tareqimbasher** [comment]
#236 is merged and fixes this issue. Latest available version will now show the latest version of the package's "channel". For example, Serilog `3.0.1` shows there is a later version: `4.0.0`, this is the latest "stable" version. Serilog `4.0.1-dev-02205` on the otherhand, being a pre-release, will show there is a later pre-release version: `4.0.1-dev-02209`

![image](https://github.com/user-attachments/assets/7224f38a-db34-4cdd-836b-339c4f4e84d0)
