### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by brendon-agileBridge** [tareqimbasher/NetPad#234]
![image](https://github.com/user-attachments/assets/a9ec3bb2-d69b-4c67-97d0-86a19e028c80)

**Comment by tareqimbasher** [comment]
@brendon-agileBridge please checkout this section of the Troubleshooting wiki page: https://github.com/tareqimbasher/NetPad/wiki/Troubleshooting#netpad-does-not-start-on-windows-error-listen-eacces-permission-denied

**Comment by tareqimbasher** [comment]
@brendon-agileBridge does the fix listed above resolve your issue?

**Comment by brendon-agileBridge** [comment]
hi the program was working for months,
on one specific day it failed, and then resolved it self the next day.

This was before i could try the listed fix

**Comment by tareqimbasher** [comment]
Thanks for letting me know. It's interesting, there is some upstream component that freaks out under certain situations that have to do with one's network config. The listed fix usually does the trick though..

Anywho, thanks for reporting back.
