### ISSUE TITLE
When closing the application, a JavaScript error occurs in the main process

### ISSUE THREAD

**Issue by thenasim** [tareqimbasher/NetPad#244]
![Screenshot 2024-08-12 191124](https://github.com/user-attachments/assets/0a44dea1-33fd-4398-af16-7b8c71b16ebf)

I often get this error when I close the application. The main window closes, and then I receive this error message.
NetPad Version: 0.7.2

**Comment by tareqimbasher** [comment]
Thank you for reporting. Will fix in next release.
