### ISSUE TITLE
Compilation error of script (ambiguous reference)

### ISSUE THREAD

**Issue by dilvid83** [tareqimbasher/NetPad#246]
I've not looked into the NetPad code yet but pretty sure I know what it is and how to solve it. I think we need to fully qualify all functions within the NetPad app itself. We get an error when trying a simple script after bringing in some Nuget Packages. It's a simple 'ambiguous reference' error but obviously stops us using certain packages. So far I've only found one nuget package which causes this but haven't been looking.

If you bring in 'FuzzySharp' and do a simple script like the following...

```c#
var productName1 = "";
var productName2 = "";

Fuzz.Ratio(productName1, productName2).Dump();
``` 

You will get the following error when 'Play' is pressed.

```
Compilation failed:
(434,9): error CS0104: 'Process' is an ambiguous reference between 'System.Diagnostics.Process' and 'FuzzySharp.Process'
(437,29): error CS0104: 'Process' is an ambiguous reference between 'System.Diagnostics.Process' and 'FuzzySharp.Process'
(438,27): error CS1061: 'Process?' does not contain a definition for 'EnableRaisingEvents' and no accessible extension method 'EnableRaisingEvents' accepting a first argument of type 'Process?' could be found (are you missing a using directive or an assembly reference?)
(445,13): error CS0019: Operator '!=' cannot be applied to operands of type 'Process?' and '<null>'
(447,27): error CS1061: 'Process?' does not contain a definition for 'Exited' and no accessible extension method 'Exited' accepting a first argument of type 'Process?' could be found (are you missing a using directive or an assembly reference?)
``` 

Raising to track but will take a look and see what I can fix.

**Comment by tareqimbasher** [comment]
Yep that sure looks like we need to fully qualify the usage of `Process`. I bet it's happening in the embedded [Program file](https://github.com/tareqimbasher/NetPad/blob/main/src%2FCore%2FNetPad.Runtime%2FExecutionModel%2FExternal%2FEmbeddedCode%2FProgram.cs) that is included in every running script. Fully qualifying the type there and removing the using should most likely take care of this.

**Comment by tareqimbasher** [comment]
#257 is merged and fixes this issue. Will go out with next release soon.
