### ISSUE TITLE
Pluralized table names

### ISSUE THREAD

**Issue by faahiero** [tareqimbasher/NetPad#267]
The problem mentioned in issue #215 was solved. Now I can connect and visualize the database table structure correctly. But all tables are pluralized. I think it's because the DbSet<T> properties (`DbSet<Author> Program.Authors { get; `}), but it would be nice, or more accurate, if the tables had the names they received when the database was created.

E.g.: 
![image](https://github.com/user-attachments/assets/fda9432f-e0a2-4029-86ac-76f75309fa64)

![image](https://github.com/user-attachments/assets/559fe9fb-cb28-472e-9231-ca0d7b5a3ab9)

**Comment by tareqimbasher** [comment]
Pluralization does indeed come from the default behavior of EF pluralizing `DbSets`, but if you prefer them singular you can change that in the connection properties window.

Also as a side note, hovering over a table will show it's actual name.

**Comment by faahiero** [comment]
I get it! Found the option. Closing Issue!

![image](https://github.com/user-attachments/assets/25e3322d-6f2e-4f2b-8af7-c82f2016561d)
