### ISSUE TITLE
Can't install NetPad v0.8.0 on Apple Silicon

### ISSUE THREAD

**Issue by lulunac27a** [tareqimbasher/NetPad#271]
When I download [netpad_vnext-0.8.0-mac-arm64.dmg](https://github.com/tareqimbasher/NetPad/releases/download/v0.8.0/netpad_vnext-0.8.0-mac-arm64.dmg), I can't install NetPad version 0.8.0 (latest version) because “NetPad vNext” is damaged and can’t be opened. You should eject the disk image.

**Comment by tareqimbasher** [comment]
Does [this](https://github.com/tareqimbasher/NetPad/wiki/Troubleshooting#netpad-is-damaged-and-cant-be-opened) solve your issue?

**Comment by imran-uk** [comment]
Thanks @tareqimbasher - this worked for me.

I think I recall doing this for the previous version, maybe there is a way to link https://github.com/tareqimbasher/NetPad/wiki/Troubleshooting#netpad-is-damaged-and-cant-be-opened from the releases page?

Good that .net8 is supported, we're using it all the time now that .net6 will be out-of-support next month.

**Comment by lulunac27a** [comment]
It works when I use the command by following the troubleshooting steps or I installed Homebrew version on Apple silicon.
