### ISSUE TITLE
Kubuntu 24.10 - Error while opening : the SUID sandbox helper binary was found, but is not configured correctly

### ISSUE THREAD

**Issue by tale80** [tareqimbasher/NetPad#272]
Hello,

I just installed NetPad 0.8.0 via deb package on Kubuntu 24.10 (Beta) but I have an error while opening it.

`[23617:1009/234200.390715:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/NetPad/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)`

result of checking /opt/netpad rights : 

```
me@computer:/opt/NetPad$ ls -l
total 207112
-rw-r--r-- 1 root root    130438 oct.   1 17:54 chrome_100_percent.pak
-rw-r--r-- 1 root root    181852 oct.   1 17:54 chrome_200_percent.pak
-rwxr-xr-x 1 root root   1271152 oct.   1 17:54 chrome_crashpad_handler
-rwxr-xr-x 1 root root     54000 oct.   1 17:54 chrome-sandbox
-rw-r--r-- 1 root root  10541296 oct.   1 17:54 icudtl.dat
-rwxr-xr-x 1 root root    250496 oct.   1 17:54 libEGL.so
-rwxr-xr-x 1 root root   2855152 oct.   1 17:54 libffmpeg.so
-rwxr-xr-x 1 root root   6536800 oct.   1 17:54 libGLESv2.so
-rwxr-xr-x 1 root root   4497352 oct.   1 17:54 libvk_swiftshader.so
-rwxr-xr-x 1 root root   6403496 oct.   1 17:54 libvulkan.so.1
-rw-r--r-- 1 root root      1096 oct.   1 17:54 LICENSE.electron.txt
-rw-r--r-- 1 root root   6762117 oct.   1 17:54 LICENSES.chromium.html
drwxr-xr-x 2 root root      4096 oct.   9 23:35 locales
-rwxr-xr-x 1 root root 166452616 oct.   1 17:54 netpad
drwxr-xr-x 3 root root      4096 oct.   9 23:35 resources
-rw-r--r-- 1 root root   5458671 oct.   1 17:54 resources.pak
-rw-r--r-- 1 root root    162352 oct.   1 17:54 snapshot_blob.bin
-rw-r--r-- 1 root root    476792 oct.   1 17:54 v8_context_snapshot.bin
-rw-r--r-- 1 root root       107 oct.   1 17:54 vk_swiftshader_icd.json
```

**Comment by lpreiner** [comment]
> sudo chmod 4755 chrome-sandbox

Thanks -- this resolves the same issue on Ubuntu 24.04 LTS.

**Comment by tareqimbasher** [comment]
Thank you @tale80 for the issue and fix. Do you know if this is an issue with NetPad that I can fix or if it's more of an environment thing or related to chrome-sandbox specifically?

**Comment by lpreiner** [comment]
> Thank you @tale80 for the issue and fix. Do you know if this is an issue with NetPad that I can fix or if it's more of an environment thing or related to chrome-sandbox specifically?

From what I can tell, this is an AppArmor issue starting with Ubuntu 24 that impacts [Electron](https://github.com/electron/electron/issues/42510).

**Comment by tale80** [comment]
> Thank you @tale80 for the issue and fix. Do you know if this is an issue with NetPad that I can fix or if it's more of an environment thing or related to chrome-sandbox specifically?

sorry @tareqimbasher, no I don't know much how to solve this directly on your side. I'm not an expert in linux packaging, maybe if you can do a kind of custom action to check and set directly rights on the chrome-sandbox file it can works, but it doesn't sound like a good fix

or like the ticket mentioned by @lpreiner said, maybe work on AppArmor profile, but I don't know this feature and how to catch this.

But, just to mentioned I have discovered NetApp recently and I find it very cool. Good job !

**Comment by matiasbenedetto** [comment]
> I have corrected the mode for chrome-sandbox with
> sudo chmod 4755 chrome-sandbox

This is not working for me.

```
matias@xpsk:~/Applications$ ./cursor-0.42.3x86_64.AppImage 
[16483:1029/103217.538362:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_cursorfE0XgO/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

```
matias@xpsk:~$ sudo chmod 4755 chrome-sandbox
chmod: cannot access 'chrome-sandbox': No such file or directory

```

```
matias@xpsk:~/Applications$  chmod 4755 /tmp/.mount_cursorfE0XgO/chrome-sandbox 
chmod: cannot access '/tmp/.mount_cursorfE0XgO/chrome-sandbox': No such file or directory
```

**Comment by candoumbe** [comment]
> > I have corrected the mode for chrome-sandbox with
> > sudo chmod 4755 chrome-sandbox
> 
> This is not working for me.
> 
> ```
> matias@xpsk:~/Applications$ ./cursor-0.42.3x86_64.AppImage 
> [16483:1029/103217.538362:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_cursorfE0XgO/chrome-sandbox is owned by root and has mode 4755.
> Trace/breakpoint trap (core dumped)
> ```
> 
> ```
> matias@xpsk:~$ sudo chmod 4755 chrome-sandbox
> chmod: cannot access 'chrome-sandbox': No such file or directory
> ```
> 
> ```
> matias@xpsk:~/Applications$  chmod 4755 /tmp/.mount_cursorfE0XgO/chrome-sandbox 
> chmod: cannot access '/tmp/.mount_cursorfE0XgO/chrome-sandbox': No such file or directory
> ```
@matiasbenedetto 
The `sudo chmod 4755 /opt/NetPad/chrome-sandbox` command worked for me.
