### ISSUE TITLE
Launching as a web app?

### ISSUE THREAD

**Issue by mcintyre321** [tareqimbasher/NetPad#278]
Are there instructions on how to launch netpad as a web app? I've tried running locally in Rider but I'm getting issues around SPA/proxy settings. However, that's not exactly what I'm trying to achieve.

I would like to host a web app where team members can execute predefined scripts (e.g. I might create a docker image with a library of scripts) and host that somewhere.

There are some AuthZ/AuthN hurdles also think about, and ideally a readonly mode for scripts, but first step would be to understand if the above is possible.

**Comment by tareqimbasher** [comment]
@mcintyre321 I updated the [CONTRIBUTING.md](https://github.com/tareqimbasher/NetPad/blob/main/CONTRIBUTING.md#web-browser) file and made it a bit clearer on how to run the web app. Please let me know if you have any issues.
