### ISSUE TITLE
result window is not sticky to the query window session during continuous execution.

### ISSUE THREAD

**Issue by fasilmarshooq** [tareqimbasher/NetPad#280]
When executing two different stuffs it would be great if the result window is sticky just like how we had in the linqpad.
Refer to this video -> 

https://github.com/user-attachments/assets/2f76403b-d15b-4f77-8850-0b39ba42058e

It worked fine the execution is not continuous, example just print something out. But it is not working when one of them is continuous execution. For example, in my case, one window is a Kafka consumer and the other is the producer.

**Comment by tareqimbasher** [comment]
Hmm this might be a regression actually. I'll get this fixed.

**Comment by tareqimbasher** [comment]
Fix merged and will go out with next update.
