### ISSUE TITLE
Multiple NuGet sources issue

### ISSUE THREAD

**Issue by d3lboy** [tareqimbasher/NetPad#287]
I’ve encountered an issue:

When multiple package sources are configured, such as NuGet.org and a private source, and access to the private source is restricted (e.g., due to permission issues), no results are displayed from NuGet.org either.

You can find attached some logs.
[log20241108-partial.txt](https://github.com/user-attachments/files/17677033/log20241108-partial.txt)

**Comment by tareqimbasher** [comment]
@d3lboy fix is merged. Will go out with next release. Thank you for reporting.

**Comment by d3lboy** [comment]
Thank you @tareqimbasher

**Comment by tareqimbasher** [comment]
@d3lboy [v0.9.0](https://github.com/tareqimbasher/NetPad/releases/tag/v0.9.0) is now out with this fix.
