### ISSUE TITLE
Can run scripts using Flaui but cannot recognize relevent  namespace and methods

### ISSUE THREAD

**Issue by ShannonZ** [tareqimbasher/NetPad#294]
![image](https://github.com/user-attachments/assets/5e2be865-e97b-4a23-84f0-77f30bd6b9b5)

**Comment by tareqimbasher** [comment]
Do you see the same issue if you restart NetPad? What about if you use .NET 8 instead of 9, do you still see the issue?

**Comment by ShannonZ** [comment]
> Do you see the same issue if you restart NetPad? What about if you use .NET 8 instead of 9, do you still see the issue?

Solved after I restart NetPad
