### ISSUE TITLE
Change nuget package source URL

### ISSUE THREAD

**Issue by EmilySamantha80** [tareqimbasher/NetPad#295]
I'm not sure if this is a "me thing" or if it's something that's not available to change, but is there a way in the settings to change the nuget package source to a different address? We have a Nuget proxy that holds all of our internally developed packages as well as the usual public nuget packages.

**Comment by EmilySamantha80** [comment]
Looking through the code it seems to be hardcoded in NuGetPackageProvider.cs, so I think I answered my own question. Is this something that could be configured in the future?

**Comment by tareqimbasher** [comment]
The answer is yes, you can add/edit the package source. NetPad uses your global Nuget.config file, so just locate your nuget config file, and add any package sources you'd like to it.

See [this](https://learn.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior) for where to locate it, typically you'd make your changes to the user-level nuget.config
