### ISSUE TITLE
Console.ReadLine doesn't work when using a class with Main method

### ISSUE THREAD

**Issue by EmilySamantha80** [tareqimbasher/NetPad#300]
I'm having an issue in 0.8.0 where Console.ReadLine isn't working inside of a class with a Main method. The prompt never shows up and the program hangs. In addition, Console.WriteLine shows up with a red font. Here is the sample code:
```
class TestClass
{
    static void Main(string[] args)
    {
        Console.WriteLine("Enter a string:");
        string input = Console.ReadLine() ?? "";
        Console.WriteLine($"Your input was: {input}");
    }
}
```

The output I get is as follows:
<img width="507" alt="NetPad ReadLine Issue 1" src="https://github.com/user-attachments/assets/dd2e9475-a961-4b1b-8532-10aa8442e940" />

Note that when using just the 3 lines of code inside of the Main function (without the class), everything works as expected:
<img width="520" alt="NetPad ReadLine Issue 2" src="https://github.com/user-attachments/assets/b38b6eb9-2b3c-4cc5-8219-fa6248db94b8" />

**Comment by tareqimbasher** [comment]
Check out this wiki: https://github.com/tareqimbasher/NetPad/wiki/How-Tos

**Comment by EmilySamantha80** [comment]
Well I feel dumb. Searched around and didn't see that particular section.

Thanks! Works like a charm.

**Comment by tareqimbasher** [comment]
No worries :) to be fair I only added it as a wiki entry a couple weeks ago.
