### ISSUE TITLE
Monoco options link is broken

### ISSUE THREAD

**Issue by ChristopherHaws** [tareqimbasher/NetPad#37]
When you click on the link, it brings you here:
https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.IEditorOptions.html

But the correct URL is:
https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorOptions.html

![image](https://user-images.githubusercontent.com/5934505/226206734-dd9a18f2-6008-45f5-8c94-ec6b18aa8fcb.png)

**Comment by tareqimbasher** [comment]
@ChristopherHaws Oh, they must've moved it. The corrected link will go out with the next release.

**Comment by ChristopherHaws** [comment]
No worries, I figured that's probably what happened ^_^
