### ISSUE TITLE
Native support?

### ISSUE THREAD

**Issue by sonerfromnurland** [tareqimbasher/NetPad#43]
Does it support natively Silicon chips? It seems there is on x64 version for macs.

**Comment by tareqimbasher** [comment]
@sonerfromnurland I do plan to release Apple Silicon builds in the near future, but as of right now only a x64 build exists for macs. It seems more users are using M1/M2 chips these days so its definitely something that will be supported soon. It would be nice to see how many users are on ARM vs x86 macs but I couldn't find any online source that has any stats on that.

**Comment by tareqimbasher** [comment]
@sonerfromnurland you can also see https://github.com/tareqimbasher/NetPad/issues/42#issuecomment-1574490689 for a native Apple Silicon build.

**Comment by tareqimbasher** [comment]
New macOS ARM builds are now available in the latest [v0.3.1 release](https://github.com/tareqimbasher/NetPad/releases/tag/v0.3.1)!
