### ISSUE TITLE
Ctrl+R throws error

### ISSUE THREAD

**Issue by ChristopherHaws** [tareqimbasher/NetPad#56]
Hey there! I am so used to pressing `ctrl+r` to show/hide the results window in LINQPad, I accidently keep calling it in NetPad (I know it is the reload shortcut). Everytime I press it, I get the following error:

![image](https://github.com/tareqimbasher/NetPad/assets/5934505/f8fe9cfa-85d9-4ce7-b302-19770d90ca28)

Any chance we can get `ctrl+r` to show/hide the results instead of reloading the browser window?

Thanks! :)

**Comment by tareqimbasher** [comment]
Yeah, good idea. I'll add that to the next release. As for that specific error, its an upstream bug that I'm hoping will get a resolution soon.

**Comment by tareqimbasher** [comment]
PR #57 merged. Change will go out with next release.
