### ISSUE TITLE
Is there a way to output raw html to the output window for formatting?

### ISSUE THREAD

**Issue by planetclegg** [tareqimbasher/NetPad#64]
I've tried various things such as:
```
new RawScriptOutput("<i>asdf</i>").Dump();
new HtmlScriptOutput("<i>asdf</i>").Dump();
```
But these introspect the object and render as if they were arbitrary objects.   I guess this isn't the intended usage.

Looking for something similar to RawHtml() in LP.

**Comment by planetclegg** [comment]
I should add, I also want to do a little more than just text formatting ;-)

**Comment by tareqimbasher** [comment]
@planetclegg not currently. However that's something I'm looking to add. I'd like to also add syntax highlighting to HTML/XML/JSON strings as well as for a number of other language formats. Hoping sometime in the next few weeks. Stay tuned!

With HTML specifically, another feature on my roadmap is to be able to write custom HTML visualizers (controls), similar to how you can write WPF/Winforms controls in LINQPad, with some hooks to be able to interact with them from your script.

>  I also want to do a little more than just text formatting

Can you give me some examples of what you're looking to do?

**Comment by planetclegg** [comment]
> Can you give me some examples of what you're looking to do?

Mostly bitmap images, using a src tag that's either local or remote, and/or possibly small images using a data-uri.   Wouldn't need it as much if I could dump them directly, but I suspect that will get tricky to do in a cross-platform way.

SVG fragments as well, although that's a rarer use-case for me.

**Comment by tareqimbasher** [comment]
Thank you for the feedback. If you can think of any other related use cases you'd like to see let me know.

**Comment by tareqimbasher** [comment]
## Update

### Adding custom HTML elements to the Output pane
Some related features coming soon: https://github.com/tareqimbasher/NetPad/issues/133#issuecomment-1831168769

### Formatting output
You'll soon be able to do:

```csharp
someObj.Dump(cssClass: "p-2 bg-light") // all Bootstrap CSS classes are available
```

This will also soon be paired with the ability to add custom CSS to style output, at which point you can specify any CSS class(es) you want and style them with custom CSS.

### Image, Video...etc Files

An API specific to dumping images, audio and video files is being worked on that will make it easy to render those types of object.

```csharp
Image.FromPath("/path/to/file").Dump();
Image.FromUri(new Uri("https://path.com/image.png")).Dump();
Image.FromBase64("data:image/png;base64,/9j/4AAQSkZJRgABAQAAAQABAAD...").Dump();
new Audio("/path/to/file").Dump();   // Audio & Video also have FromUri() and FromBase64() methods
new Video("/path/to/file").Dump();

// Opens file with default application and wait for it to exit. Omitting 'await' will skip the wait
await new Video("/path/to/file").OpenAsync();
```

**Comment by planetclegg** [comment]
Hey, that's awesome!

Is there any chance you could allow sending the raw image from C#, e.g.

var bytes = LoadBytesFromSomewhere()
Image.FromBytes(bytes).Dump() ?

Primary use case being, I'll be creating images in memory in C#.    I could certainly get by on FromBase64 for a while, but it's an extra transformation that might have limits on size

Thanks again

**Comment by tareqimbasher** [comment]
Yeah I can add a `FromBytes`, it will just convert it to Base64 internally.

There's no straightforward way AFAIK to pass along the byte array directly to an `<img/>`, no way around the ~33% increase in file size being rendered when using the `FromBytes` and `FromBase64` methods.

**Comment by tareqimbasher** [comment]
@planetclegg check out the new v0.7.0 for experimental support for HTML rendering.

**Comment by planetclegg** [comment]
Thanks for pinging me.   I've been playing with it tonight, mostly just images at this point, looks pretty good so far.   I'll mess around with some of the html stuff soon.   Thanks also for the wiki entry describing the various new dump features, that will be very helpful.

**Comment by planetclegg** [comment]
So far so good, I played around a bit with your examples on injecting HTML into the output window....     With all the HTML related Dump() functionality, is there any way to get click events (or any DOM/js events) back to the C# script?  I'm guessing the answer is "no" or "not yet", but it would be useful enough that it's worth asking.

**Comment by tareqimbasher** [comment]
As you guessed, not yet. C#/JS interop is anything but trivial, before driving down that road I'm going to give Blazor support a good look. If it turns out it's reasonably possible to integrate into NetPad, that would be a much more robust solution than rolling something custom, and I think would be a major boon for this project :crossed_fingers:

That being said, I have been holding myself back on implementing at least basic support for some common events like button clicks and form submissions.. really trying to not let the thrill get the better of me :smile:

**Comment by planetclegg** [comment]
@tareqimbasher is there a way to change the scaled size of a Dump()ed image?  I'm working with some larger images and it is limiting the visible size to something fairly small.  I can drag it out onto the desktop and see that it is actually the full image (which is handy), but it would be nice to set a larger bounding box

**Comment by tareqimbasher** [comment]
I'll add that in the next minor update :+1:

**Comment by planetclegg** [comment]
FWIW, I've been playing around with SkiaSharp to generate images and it's been working out fairly well.  I'm able to generate and dump a moderate-sized image and NP reports the runtime around 400ms, which is quite usable (and most of that time seems to be the initial loading of SkiaSharp for some reason).  I'm surprised using base64 encoding for the images and streaming that to the web engine is working as well as it is.

**Comment by tareqimbasher** [comment]
@planetclegg PR #203 adds the ability to control display size of media files.

Since HTML rendering will be a continually improved feature I will close this ticket but feel free to continue the discussion or open new issues requesting new features or issues you're facing.

**Comment by tareqimbasher** [comment]
@planetclegg v0.7.1 is out with the ability to size media files!
