### ISSUE TITLE
Netpad 0.4.1 for Mac M2 is broken

### ISSUE THREAD

**Issue by nZeus** [tareqimbasher/NetPad#67]
when I unzip the file and run the app, I get this error:

<img width="244" alt="image" src="https://github.com/tareqimbasher/NetPad/assets/2727326/bb13e1d8-7dfa-4306-9c64-cd6e10f15eef">

**Comment by nZeus** [comment]
Sorry guys, false alarm - I should have used `0.4.1-mac-x64.zip` instead

**Comment by tareqimbasher** [comment]
If you're on an M2 Mac, then you do infact want the ARM version. The Mac x64 version will still work for you but the ARM version is more performant and optimized for M1/M2 macs.

For the issue you described please see the note in the Download section of the README on how to resolve it. I'll include it here as well:

NetPad is not a signed application. On macOS when you run NetPad the first time you will prompted with a message saying the app is damaged and can't be opened. To resolve this run this in a terminal:

```
sudo xattr -cr /path/to/NetPad.app
```

**Comment by nZeus** [comment]
Hi @tareqimbasher.

I know about the command, but the displayed error is different (`damaged` vs `no signed`), so I didn't expect it to fix the issue.
Anyways, I tried ARM version again, applied command, and it is working!
Thank you!

**Comment by tareqimbasher** [comment]
I'll make the note clearer. Glad it's working now.
