### ISSUE TITLE
Netpad equivalent of "SubmitChanges()"?

### ISSUE THREAD

**Issue by reedperkins** [tareqimbasher/NetPad#68]
Hi @tareqimbasher !

I am so happy I stumbled across NetPad recently. Since moving to Linux, I've dearly missed LINQPad, and your re-implementation makes me feel less homesick :)

I have a dumb question -- what is the equivalent of the global SubmitChanges() in NetPad? How do I save changes after I've made modifications to an entity? There doesn't seem to be a global DbContext instance that I can access.

Thanks again for making this amazing software!

**Comment by tareqimbasher** [comment]
Hi @reedperkins,

I'm very glad you're enjoying it! Working on Linux/Mac and still being able to have access to a tool like this is one of the main reasons I developed NetPad.

NetPad uses EF core internally, so you can just do `SaveChanges'. You can also directly access the ambient DbContext with the `DataContext` property.

Welcome to NetPad, excited to have you as a user!

**Comment by tareqimbasher** [comment]
Closing this issue. Feel free to reopen it if you have any related questions.
