### ISSUE TITLE
Seeing duplicate values in intellisense results

### ISSUE THREAD

**Issue by ChristopherHaws** [tareqimbasher/NetPad#74]
Hey! Just updated to the latest release! Really amazing work you are doing :)

Just wanted to let you know, I am seeing duplicates in my intellisense:
![image](https://github.com/tareqimbasher/NetPad/assets/5934505/5ad04e1f-c24f-4f71-91c0-1f572e62d702)

**Comment by tareqimbasher** [comment]
Thank you! Glad you're enjoying it.

I wasn't able to replicate the duplication. Can you provide a sample or attach a script where you're seeing this issue?

**Comment by ChristopherHaws** [comment]
Interesting, the issue seems to only be happening on the `Matcher` type from `Microsoft.Extensions.FileSystemGlobbing`... Also, I notice that they show up different in the intellisense window (one shows the NuGet package it is in and one doesnt):

![image](https://github.com/tareqimbasher/NetPad/assets/5934505/519c55c6-a54e-4324-b0fb-d77db409fe13)
![image](https://github.com/tareqimbasher/NetPad/assets/5934505/eee313ed-8844-41d1-ae72-b39a45779f7c)

**Comment by tareqimbasher** [comment]
Couldn't find anything wrong with how we're calling into OmniSharp and I confirmed those aren't ghosts, OmniSharp is infact returning those duplicate entries, it seems something on their end. Closing as an upstream issue.
