### ISSUE TITLE
macOS Window Conventions

### ISSUE THREAD

**Issue by daviddotcs** [tareqimbasher/NetPad#82]
On macOS, the close, minimise, and maximise buttons appear on the left side of a window's title bar, and menu items appear within the system menu bar rather than within the application's window. It'd be great if NetPad could be made to feel more at-home on macOS by following these conventions.

![](https://github.com/tareqimbasher/NetPad/assets/6890281/149d4da1-4113-4ad3-b2a9-641be297a307)
*Image: NetPad above and VS Code below*

Thanks for making this though, it's a very useful utility :)

**Comment by tareqimbasher** [comment]
Yeah I agree. This is definitely something I'm planning to address. The plan is to keep the native window chrome and window controls but also integrate the menu bar with the title bar on Windows and Linux to utilize as much vertical space towards editing. On macOS, the menu will be moved to the native menu on the very top.

I gave it a quick attempt a while back but I quickly realized its something that I'll need to be a bit careful with for it to work properly in a cross-platform way. Keeping vertical real-estate as a priority, I settled on having a uniform title bar on all platforms in the meantime.

In the short term, or maybe as an alternate solution, I could introduce a couple settings:
- **Use native title bar**: Which would remove the integrated, uniform, title bar, and replace it with the native title bar as in your VS Code snapshot, and move the menu to:
  - the native menu bar, at the very top, on macOS
  - the native menu bar, below the titlebar, on Windows/Linux
- **Keep the integrated titlebar but move window controls to the left**: side for users that are used to them being on the left (ie. macOS and Linux that have configured their WM as such)

**Comment by tareqimbasher** [comment]
#107 introduces a number of settings now:
- **Titlebar**
  - Integrated: the titlebar NetPad has had so far, merges the main menu and the titlebar (default for Windows/Linux).
  - Native: Uses the OS-native window chrome and titlebar (default for macOS).
- **Window Controls Position**: position the minimize, maximize, close..etc to the right or left. This does not apply when using the Native titlebar.
  - Right (default)
  - Left
- **Main Menu Auto-Hide**: does not apply when using Native titlebar on macOS
  - Always Show (default)
  - Auto-Hide
 
This will go out with the next release.

**Comment by tareqimbasher** [comment]
Closing with publish of new v0.6.0 release.
