### ISSUE TITLE
Dump not working inside Main Method

### ISSUE THREAD

**Issue by eslamo** [tareqimbasher/NetPad#89]
I'm Using Netpad 0.4.2 on MacOS

Output from Console.WriteLine works 

but Dump is not working

```
class Tech
{
    public int Id { get; set; }
    public string Name { get; set; }
}

class Startup
{
    public static void Main()
    {
        var t = new Tech
        {
            Id = 1,
            Name = "Test Name"
        };

        Console.WriteLine("Output");
        t.Dump();
    }
}
```

**Comment by tareqimbasher** [comment]
The primary approach is to write Top-Level statements, ie:

```csharp
var t = new Tech
{
    Id = 1,
    Name = "Test Name"
};

Console.WriteLine("Output");
t.Dump();

class Tech
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

If however you still would like to have your code run within a standard `Main()` entry point rename the class to `partial class Program`:

```csharp
class Tech
{
    public int Id { get; set; }
    public string Name { get; set; }
}

partial class Program
{
    public static void Main()
    {
        var t = new Tech
        {
            Id = 1,
            Name = "Test Name"
        };

        Console.WriteLine("Output");
        t.Dump();
    }
}
```

This is because NetPad includes a partial `Program` class in your script, behind the scenes, to initialize certain runtime services to facilitate interfacing between the process running your script and NetPad itself.

**Comment by tareqimbasher** [comment]
Closing this issue. Please feel free to reopen it if you face any issues.

**Comment by sjsepan3** [comment]
@tareqimbasher :This issue resolution helped me address a different hurdle. :-)

I was wondering why public fields weren't being Dumped, but they need to be public properties

```public partial class Program
{

    static void Main(string[] args)
    {

        //simple object has public properties Dumped, but not public fields
        List<Customer> custList = new List<Customer>();
        Customer cust = default;

        cust = new Customer("Q456", "joe", 12);
        cust.Dump("cust");
        custList.Add(cust);
        
        cust = new Customer("A123", "bob", 34);
        custList.Add(cust);
        
        cust = new Customer("0789", "bill", 56);
        custList.Add(cust);
        
        custList.Count.Dump("custList count");
        custList.Dump("custList");

    }
}
// Define other methods and classes here
public class Customer
{
    public Customer(string id, string name, int value)
	{
		ID = id;
        Name = name;
        Value = value;
    }
    public string ID { get; set; }
    public string Name { get; set; }
    public int Value;
}

```

Output:

```
cust
Customer
ID	Q456
Name	joe

custList count
3

custList
List<Customer> (3 items)
ID	Name
Q456	joe
A123	bob
0789	bill

```

**Comment by tareqimbasher** [comment]
Yes! Only public properties will be dumped. Fields, public or otherwise, are not dumped. The plan is to give users more control over what gets dumped, hopefully soon.

**Comment by sjsepan3** [comment]
> Yes! Only public properties will be dumped. Fields, public or otherwise, are not dumped. The plan is to give users more control over what gets dumped, hopefully soon.

I've gone ahead and made an issue entry (#314) so that there is a place for folks to discuss what the behavior might look like.
