### ISSUE TITLE
Can't stop a runaway query without killing the app

### ISSUE THREAD

**Issue by ChristopherHaws** [tareqimbasher/NetPad#98]
I'm unable to stop a runaway query without closing NetPad. It seems to only happen when logging to the console or using `.Dump()`.

## Minimal Repro
```cs
while (true) {
    Console.WriteLine(DateTime.Now);
}
```

**Comment by tareqimbasher** [comment]
Thanks for reporting. Will take a look.

**Comment by tareqimbasher** [comment]
So this started me down a rabbit hole and finally had me focus on making some planned, and overdue, design changes to how script output is rendered. #112 introduces a number of changes and enhancements that include fixing this issue. It will go out with next release.

**Comment by tareqimbasher** [comment]
Will keep open till new version is released

**Comment by tareqimbasher** [comment]
Closing with publish of new v0.6.0 release.
